name: Continuous Integration (CI)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '18.x'
  CI: true  # Force le mode CI pour tous les outils

jobs:
  test-build:
    name: Test + Build
    runs-on: windows-latest

    steps:
    # Étape 1: Checkout du code
    - uses: actions/checkout@v4

    # Étape 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    # Frontend - Client
    - name: Install Frontend Dependencies
      working-directory: ./client
      run: npm ci

    - name: Run Frontend Tests
      working-directory: ./client
      run: npm test
      env:
        CI: true

    - name: Build Frontend
      working-directory: ./client
      run: npm run build

    # Backend - Server
    - name: Install Backend Dependencies
      working-directory: ./server
      run: npm ci

    - name: Run Backend Tests
      working-directory: ./server
      run: npm test
      env:
        NODE_ENV: test

    # Validation des builds
    - name: Verify Build Artifacts
      run: |
        dir .\client\dist\ /s   # Dossier de build Vite
        dir .\server\ /s
